### ISSUE TITLE
Benchmark with futures producer 

### ISSUE THREAD

**Issue by abrugh** [fede1024/kafka-benchmark#1]
Wondering if you could add futures producer to the benchmark.

**Comment by fede1024** [comment]
Added.

```
Scenario: msg_bursts_base, repeat 5 times, 10s pause after each
[...]
Average: 3964950 messages/s, 37.813 MB/s

Scenario: msg_bursts_future, repeat 5 times, 10s pause after each
[...]
Average: 2416918 messages/s, 23.050 MB/s
```

As expected, the `FutureProducer` is much slower than the `BaseProducer`. I suspect that it's mainly because of the allocations required to create futures. I'm planning to have a `StreamProducer` that won't require extra allocations.

**Comment by abrugh** [comment]
Thanks for doing this so quickly, and on the weekend no less!

Your async processing example in rust-rdkafka has a cpu_pool handling the send/delivery report in a chained manner on a per message basis ( https://github.com/fede1024/rust-rdkafka/blob/master/examples/asynchronous_processing.rs#L95 ). Do you think that method is slower than queuing up a bunch of futures and then waiting on them all? It definitely seems harder to benchmark. The cpu pool seems like a nice way to keep from blocking the main thread if it had other work to do.

**Comment by abrugh** [comment]
Looking at it again, i guess the thread pool is there for the expensive computation. My Rust is pretty weak, I'm not sure how the `and_then` chain on a spawn_fn call works.

**Comment by fede1024** [comment]
The `spawn_fn` will execute the given closure on a thread pool, and immediately return a future that will be completed once the closure finishes. `and_then` is used to chain futures together, so it will execute the next step only once the closure has been completed in the other thread.

I'm not sure what you are trying to implement. The `FutureProducer` can be used to asynchronously handle the result of message production (failures for example), not messages itself, while the async example you mention shows how to process messages asynchronously on the consumer side.

Assuming that you are talking about the consumer side: if your computation is "quick" (as in, no CPU intensive) and not blocking (no other IO operations), I suggest just to chain it to the `stream` returned by `consumer.start()`. Some nice documentation on streams can be found [here](https://tokio.rs/docs/getting-started/streams-and-sinks/), however futures-rs is probably one of the most difficult libraries to use in the Rust ecosystem, so expect a steep learning curve :)
