### ISSUE TITLE
consumer benchmark

### ISSUE THREAD

**Issue by ongardie-ebay** [fede1024/kafka-benchmark#5]
Feature request: It'd be nice to have a consumer benchmark with some posted numbers that others could compare against. Does anything like that exist? This repo appears to only have producer benchmarks today.

**Comment by ongardie-ebay** [comment]
In my application, I'm seeing BaseConsumer deliver messages at 5-6x the throughput of StreamConsumer. It'd be good to get both of these in the benchmark suite.

**Comment by ongardie-ebay** [comment]
(I suspect the unbuffered channel here may be to blame: https://docs.rs/rdkafka/0.14.1/src/rdkafka/consumer/stream_consumer.rs.html#183 , but we should have a repeatable benchmark before proposing any changes.)

**Comment by fede1024** [comment]
In some tests I did in the past the buffer didn't seem to have an effect on the consumer throughput (which I found surprising). Yeah a repeatable benchmark would be better. I'll write one (contributions are also welcome :) ).

Are you receiving small messages? That's where the extra overhead of the StreamConsumer might become noticeable.

**Comment by ongardie-ebay** [comment]
@fede1024 I found a small buffer on that channel to help a lot (throughput went from about 100MBps to about 500MBps). The messages I'm testing with average around 2KB in size.

I don't think I'll have time to contribute a benchmark soon, but if you get one started I'd be more than happy to take it for a spin in my environment.

**Comment by fede1024** [comment]
Very interesting! Thank you for running the test. I've started working on a consumer benchmark. I'll run similar tests and see if I can replicate your results.

**Comment by fede1024** [comment]
I've added a simple consumer benchmark. Indeed, a small buffer can greatly reduce the number of context switches and make the consumer considerably faster. I'll change the default buffer size in rust-rdkafka, and also make it configurable.

The `BaseConsumer` is still considerably faster than `StreamConsumer` when dealing with very small messages (10 bytes). However in more realistic benchmarks (1KB for example), the performance becomes basically identical if a buffer is used.
